# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DesignSystemComponent`.
# Please instead update this file by running `bin/tapioca dsl DesignSystemComponent`.


class DesignSystemComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
