# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EmailConfirmationMailer`.
# Please instead update this file by running `bin/tapioca dsl EmailConfirmationMailer`.


class EmailConfirmationMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def confirmation_email; end
  end
end
