# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InvitationMailer`.
# Please instead update this file by running `bin/tapioca dsl InvitationMailer`.


class InvitationMailer
  class << self
    sig { params(invitation: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def invite_email(invitation); end
  end
end
