# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncCleanerJob`.
# Please instead update this file by running `bin/tapioca dsl SyncCleanerJob`.


class SyncCleanerJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: SyncCleanerJob).void)
      ).returns(T.any(SyncCleanerJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
